send_anonymous_usage_stats: false

pizza_shop:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: pizza_shop
      threads: 4
      keyfile: "{{ env_var('SA_KEYFILE') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
    ci_defer:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: ci_defer
      threads: 4
      keyfile: "{{ env_var('SA_KEYFILE') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
    ci_clone:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: ci_clone
      threads: 4
      keyfile: "{{ env_var('SA_KEYFILE') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
  target: dev
