name: slim-ci

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  DBT_PROFILES_DIR: "${{github.workspace}}/dbt_profiles"

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set up service account key file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo ${GCP_SA_KEY} > ${{github.workspace}}/.github/key.json
          echo SA_KEYFILE= ${{github.workspace}}/.github/key.json >> $GITHUB_ENV

      - name: Install dbt dependencies
        run: |
          dbt deps --project-dir=pizza_shop --target ci
          echo $GCP_SA_KEY

      # - name: DBT Slim CI
      #   env:
      #     GCP_PROJECT: ${{ env.GCP_PROJECT_ID }}
      #     SA_KEYFILE: ${{github.workspace}}/.github/key.json
      #   run: |
      #     dbt run --profiles-dir=dbt_profiles --project-dir=pizza_shop --target ci
      #     # dbt run --profiles-dir=dbt_profiles --project-dir=pizza_shop --target ci --select state:modified+ --state prod-run-artifacts
